version: '3.5'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - php-shropshire
    environment:
      - "APP_NAME=app"
networks:
  php-shropshire:
    external: true